import { Injectable } from '@angular/core';
import { Exercise } from '../models/exercise';

@Injectable({
  providedIn: 'root'
})
export class ExerciseService {

  private exercises: Exercise[] = [];

  constructor(){

    // get key and load values or empty if no values
    let savedExercises = localStorage.getItem("exercises");
    // USED THIS AFTER EXERCISE FORM CREATED //this.exercises = savedExercises ? JSON.parse(savedExercises) : [];

    // load some hard-coded data until exercise form done
    this.exercises = [{
      "id": "1",
      "name": "Bench Press",
      "equipment": "Barbell",
      "primaryMuscleWorked": "Chest",
      "image": ""
  },
  {
    "id": "2",
    "name": "Squat",
    "equipment": "Barbell",
    "primaryMuscleWorked": "Quads",
    "image": ""
}];
  }

  getExercises(): Exercise[] {
    return this.exercises;
  }

  // returns a single Exercise model or undefined if id finds no match
  getExercise(id: string): Exercise | undefined {
    return this.exercises.find(res => res.id === id);
  }

  addExercise(exercise: Exercise): void {
    // provides an id generated by the system. Can use database primary key, _id for MongoDB later
    exercise.id = Date.now().toString();

    this.exercises.push(exercise);
    localStorage.setItem("exercises", JSON.stringify(this.exercises));
  }

  updateExercise(updatedExercise: Exercise): void {
    let index = this.exercises.findIndex(res => res.id === updatedExercise.id);
    localStorage.setItem("exercises", JSON.stringify(this.exercises));
  }
}
